name: "Wake Word Bridge"
version: "1.0.0"
slug: "wakeword_bridge"
description: "UDP to Wyoming Wake Word Bridge"
build_from:
  aarch64: ghcr.io/home-assistant/{arch}-base
  amd64:   ghcr.io/home-assistant/{arch}-base
  armv7:   ghcr.io/home-assistant/{arch}-base
  armhf:   ghcr.io/home-assistant/{arch}-base
  i386:    ghcr.io/home-assistant/{arch}-base
startup: services
boot: auto
host_network: true
map:
  - type: share
  - type: addons
ports:
  "10400/udp": 10400
options: {}
schema:
  {}
