name: "Wake Word Bridge"
version: "1.0.0"
slug: "wakeword_bridge"
description: "UDP ‑ to ‑ Wyoming wake word bridge"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
host_network: true
map:
  - type: config
    read_only: true
ports:
  "10400/udp": 10400
  options:
  mqtt_host: "homeassistant"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  site_id: "nspanel"

schema:
  mqtt_host: "str"
  mqtt_port: "int"
  mqtt_username: "str"
  mqtt_password: "str"
  site_id: "str"
commands:
  start: "/run.sh"