# wakeword_bridge/config.yaml
name: Wake Word Bridge
version: "1.0.0"
slug: wakeword_bridge
description: UDP-to-Wyoming wake-word bridge.
init: false          # container runs once, so leave false
startup: services    # 'services' = start with Supervisor
host_network: true
hassio_api: false
hassio_role: default
# panel_icon / panel_title are optional – you can drop them
schema:
  mqtt_host: str?
  mqtt_port: port?
  mqtt_username: str?
  mqtt_password: str?
  site_id: str?
