# wakeword_bridge/config.yaml
name: Wake Word Bridge
version: "1.0.0"
slug: wakeword_bridge
description: UDP → Wyoming wake-word bridge
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services        # start with Supervisor
boot: auto
init: false              # script exits – container kept by s6
host_network: true

# Supervisor passes BUILD_FROM -> Docker ARG BUILD_FROM
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11
  amd64:  ghcr.io/home-assistant/amd64-base-python:3.11
  armv7:  ghcr.io/home-assistant/armv7-base-python:3.11
  armhf:  ghcr.io/home-assistant/armhf-base-python:3.11
  i386:   ghcr.io/home-assistant/i386-base-python:3.11

ports:
  10400/udp: 10400

options:
  mqtt_host: homeassistant
  mqtt_port: 1883
  mqtt_username: nspanel
  mqtt_password: changeme
  site_id: nspanel

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  site_id: str
