name: "Wake Word Bridge"
version: "1.0.0"
slug: "wakeword_bridge"
description: "UDP ‑ to ‑ Wyoming wake word bridge"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
host_network: true
map:
  - type: config
    read_only: true
ports:
  "10400/udp": 10400
commands:
  start: "/run.sh"